version: '3.9'
services:
  metabase:
    image: metabase/metabase:v0.47.6
    volumes:
    - /dev/urandom:/dev/random:ro
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=postgres
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:16.0-bullseye
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - metanet1

volumes:
  postgres_db:

networks:
  metanet1:
    name: metanet1
    driver: bridge
