version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:3306:3306
    volumes:
      - wp_mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=change_this # change_this
      - MYSQL_PASSWORD=change_this  # change_this
      - MYSQL_USER=change_this # change_this
      - MYSQL_DATABASE=change_this # change_this
    labels:
      logging: "promtail"
      logging_jobname: "wp-mysql"

  wordpress:
    image: wordpress:php8.2
    restart: unless-stopped
    # ports:
    #   - 8081:80
    environment:
      - WORDPRESS_DB_HOST=change_this # change_this
      - WORDPRESS_DB_USER=change_this # change_this
      - WORDPRESS_DB_PASSWORD=change_this # change_this
      - WORDPRESS_DB_NAME=change_this # change_this
      - WORDPRESS_TABLE_PREFIX=change_this # change_this
      
      - VIRTUAL_HOST=example.com
      - VIRTUAL_PORT=80
    volumes:
      - wp_data:/var/www/html
    labels:
      logging: "promtail"
      logging_jobname: "wp"

volumes:
  wp_mysql:
  wp_data: