global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: 
          - '127.0.0.1:9090'

  # Example job for nginx_exporter
  - job_name: 'nginx_exporter'
    scrape_interval: 5s
    basic_auth:
      username: nginx_exporter # change this
      password: nginx_exporter_password # change this
    static_configs: # change this
      - targets: 
          - '127.0.0.1:9113'
        labels:
          group: 'main'
          server: 'main_server'
          environment: 'production'
      
      - targets: 
          - '123.134.211.124:9113'
        labels:
          group: 'staging'
          server: 'staging_server'
          environment: 'staging'

  # Example job for node_exporter
  - job_name: 'node_exporter'
    scrape_interval: 5s
    basic_auth:
      username: node_exporter  # change this
      password: node_exporter_password  # change this
    static_configs: # change this
      - targets: 
          - '127.0.0.1:9113'
        labels:
          group: 'main'
          server: 'main_server'
          environment: 'production'
      
      - targets: 
          - '123.134.211.124:9113'
        labels:
          group: 'staging'
          server: 'staging_server'
          environment: 'staging'

